spring:
  config:
    activate:
      on-profile: prod
  datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5433/company1
      username: postgres
      password: postgres
  jpa:
    database-platform: postgres
    properties:
        hibernate:
          jdbc:
            lob:
              non_contextual_creation: true
          dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
enabled: true
flyway:
  user: postgres
  password: postgres
  schemas: test
