spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/company1
    username: postgres
    password: postgres
  jpa:
    database-platform: postgres
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
enabled: true
flyway:
  user: postgres
  password: postgres
  schemas: test
